language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -r requirements.txt
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: H2VW2EBj+XOjBQQPrnz1nQF4gOPT0T6bJi3FgSNEPIFqAPxjnLLf2RRj30v6ucW4iCAQaB03/5SbtexE6VDEuoQQeMjvQzC+JAdNv882G8rshHMfYYCwKAHspppvVlpgYXLAJtkcVVGNgjeYNjNkn4zMov+G6wlKhZa9rvr+zrncflDYPwBSX+1P9zf5mW7arzUlWbJkLnKJtLYvc5xGa2pqDM6QqeopVthXl4PpzUiiUYRRvaYkkKO9g/cCcE0Hw401+jPIKMuWeIgfW5gdxXmmDPYYLKAjo/IpfqiRyFHPZ11JsjAWJZeZsJCDmRT5aUrp8++LVJ+i9GFA3VxJ7EWOMnr5QLzbKhe/AoorLsoAMuvx9LZO+u/AjD8DSB9mvC9zzgcBx4TUJtPMU2Hph/JreT5Nb0IRF0SkKdMlRpazbe2vfUq8m/jPBd4NB0f62i5a0dZSjz6OLIOYcEjRONn0Hl3yO/o0iCtH4OHTcKKHqaiLFmfYm/5JffFwagw7o4YmlLNMFrU184wsX6cCD/2wxIolAkiKPttZHoZUsGB+ygrr25BJcDd50y+NTrBWIEVwqUd5z16BXOFPCMhATYOIOPnmFN1hEzK1r+3i1UHHiMerWWusVvRi0k7qPdLCkZegjiG9MMdCj+QwpfZKCNoapOYBbqLvfuVf7ZkyyJE=
  on:
    tags: true
    repo: vinid/cade
    python: 3.8
skip_cleanup: true
